#!/bin/zsh

# Add fypm and fysm to PATH
export PATH=$PATH:$FYPM_DIR/scripts
export PATH=$PATH:$FYSM_DIR/scripts
source $FYW_DIR/config/vars


source $FYW_DIR/config/aliases


# Init some fysm scripts if it is the initialization of the system
if test ! -e "$INIT_LOCK"; then
    mkdir "$FYSM_TEMP"

    source "$FYSM_DIR"/config/init_scheduler

    echo "" > "$INIT_LOCK"
fi
