#!/bin/zsh
# Add fypm and fysm to PATH
export PATH=$PATH:$FYPM_DIR/scripts/pending
export PATH=$PATH:$FYSM_DIR/scripts

# Tmp export 
export TWBIN=$FYPM_DIR/scripts/pending
export MYBIN=$FYSM_DIR/scripts

source $FYW_DIR/config/vars
source $FYW_DIR/config/aliases

# Init some fysm scripts if it is the initialization of the system
if test ! -e "$INIT_LOCK"; then
    # Set keyboard layout
    setxkbmap -layout us -variant altgr-intl &

    mkdir "$FYSM_TEMP"

    source "$FYW_DIR"/config/init_scheduler
    
    _task_poly_daemon_ >> /dev/null 2>&1 & disown

    # _verify_eventual_tasks_
    # _verify_active_tasks_ >> /dev/null 2>&1 &
    # _verify_alarm_tasks_ >> "$FYSM_PERMA_LOGS/fypm/_verify_alarm_tasks_$(date +%Y-%m-%d)" 2>&1 &

    echo "" > "$INIT_LOCK"
fi
